speech-dispatcher: add piper support [WIP Doesn't work at the moment]
buildPhase fails after compiling while linking with the following error

```txt
  CXXLD    sd_cxxpiper
/nix/store/dc9vaz50jg7mibk9xvqw5dqv89cxzla3-binutils-2.44/bin/ld: sd_cxxpiper-cxxpiper.o: undefined reference to symbol 'OrtGetApiBase@@VERS_1.22.2'
/nix/store/dc9vaz50jg7mibk9xvqw5dqv89cxzla3-binutils-2.44/bin/ld: /nix/store/ahyx7aa9qgry9d81r6w3p7aljm04y8yp-onnxruntime-1.22.2/lib/libonnxruntime.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```